# Generated by Django 2.0.6 on 2018-07-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
