# Generated by Django 2.0.6 on 2018-07-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='food',
            old_name='ordered',
            new_name='ordered_times',
        ),
        migrations.RemoveField(
            model_name='food',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodsapp.Food'),
        ),
    ]
