# Generated by Django 2.0.6 on 2018-07-14 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsapp', '0002_auto_20180712_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
